import Head from 'next/head'

export default function Legos() {
    return (
        <>
            <Head>
                <title>Ivan Ray Altomera - Legos</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="min-h-screen bg-white flex justify-center items-center">
                <h1 className="text-gray-400 text-[3rem]">Work in Progress</h1>
            </main>
        </>
    )
}
