import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ivan Ray Altomera - Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-white text-gray-800">
        <div className="mx-auto max-w-7xl py-20 px-6 lg:py-24">
          <div>
            <h1 className="text-5xl font-black">Ivan Ray Altomera</h1>
            <div className="relative z-10 grid grid-cols-1 gap-10 lg:grid-cols-4 xl:gap-24 mt-5">
              <h2 className="text-2xl">Software Engineer</h2>
              <div className="grid-3 xl:grid-3 mt-5 gap-4 border-t-2 border-gray-300 pt-4 lg:col-span-3 lg:flex lg:justify-between">
                <div className="flex items-center">
                  <div>
                    <div className="text-sm font-semibold">Email</div>
                    <div>
                      <a href="mailto:irayspacii@gmail.com" target="_blank" rel="noreferrer">
                        irayspacii@gmail.com
                      </a>
                    </div>
                  </div>
                </div>
                <div className="flex items-center">
                  <div>
                    <div className="text-sm font-semibold">GitHub</div>
                    <div>
                      <a href="https://github.com/irayspace" target="_blank" rel="noreferrer">
                        github.com/irayspace
                      </a>
                    </div>
                  </div>
                </div>
                <div className="flex items-center">
                </div>
              </div>
            </div>
          </div>
          <div className="grid grid-cols-3 mt-12 items-start gap-10 lg:mt-24 lg:gap-24">
            <div className="lg:col-span-2">
              <h3 className="text-3xl font-bold border-b-2 border-gray-300 pb-4 mb-7">Work Experience</h3>
              <div className="grid grid-cols-3 gap-x-6">
                <div>
                  <h4>Secret</h4>
                  <div>Sept. 2021 - Present</div>
                </div>
                <div className="lg:col-span-2">
                  <h4>Job Title</h4>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex suscipit, magni rerum repellendus quaerat debitis explicabo unde officia laudantium, id numquam at provident vel soluta ullam harum ad fugiat doloribus!</p>
                </div>
              </div>
            </div>
            <div>
              <h3 className="text-3xl font-bold border-b-2 border-gray-300 pb-4 mb-7">Summary</h3>
              <p>
                For the first 5 years of my career, I have been helping in implementing various web/mobile apps to small/medium enterprises (SMEs)—Point-of-Sale (PoS) and Enterprise Resource Planning (ERP) business solutions.
              </p>
              <h3 className="text-3xl font-bold border-b-2 border-gray-300 pb-4 mb-7 mt-12">Skills</h3>
              <h4 className="text-lg font-semibold">Programming Languages</h4>
              <ul className="list-disc pl-5 mt-5 mb-5">
                <li>Python</li>
                <li>Dart</li>
                <li>JavaScript</li>
                <li>TypeScript</li>
                <li>Rust</li>
              </ul>
              <h4 className="text-lg font-semibold">Web & Mobile Frameworks</h4>
              <ul className="list-disc pl-5 mt-5 mb-5">
                <li>React.js</li>
                <li>Next.js</li>
                <li>Flutter</li>
              </ul>
              <h4 className="text-lg font-semibold">Backend Technologies</h4>
              <ul className="list-disc pl-5 mt-5 mb-5">
                <li>Cloud Firestore</li>
                <li>Cloud Functions</li>
                <li>Django</li>
                <li>FastAPI</li>
              </ul>
              <h3 className="text-3xl font-bold border-b-2 border-gray-300 pb-4 mb-7 mt-12">Education</h3>
              <h4 className="text-lg font-semibold">Xavier University - Ateneo de Cagayan</h4>
              <div>BS in Computer Science, 2018</div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
