import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ivan Ray Altomera - Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-white text-gray-800">
        <div className="mx-auto max-w-7xl py-20 px-6 lg:py-24">
          <div>
            <h1 className="text-5xl font-black">Ivan Ray Altomera</h1>
            <div className="relative z-10 grid grid-cols-1 gap-10 lg:grid-cols-4 xl:gap-24 mt-5">
              <h2 className="text-2xl">Software Engineer</h2>
              <div className="grid-3 xl:grid-3 mt-5 gap-4 border-t-2 border-gray-300 pt-4 lg:col-span-3 lg:flex lg:justify-between">
                <div className="flex items-center">
                  <div>
                    <div className="text-sm font-semibold">Email</div>
                    <div>
                      <a href="mailto:irayspacii@gmail.com" target="_blank" rel="noreferrer">
                        irayspacii@gmail.com
                      </a>
                    </div>
                  </div>
                </div>
                <div className="flex items-center">
                  <div>
                    <div className="text-sm font-semibold">GitHub</div>
                    <div>
                      <a href="https://github.com/irayspace" target="_blank" rel="noreferrer">
                        github.com/irayspace
                      </a>
                    </div>
                  </div>
                </div>
                <div className="flex items-center">
                </div>
              </div>
            </div>
          </div>
          <div className="grid grid-cols-3 mt-12 items-start gap-10 lg:mt-24 lg:gap-24">
            <div className="lg:col-span-2">
              <h3 className="text-3xl font-bold border-b-2 border-gray-300 pb-4 mb-7">Work Experience</h3>
              <div className="grid grid-cols-3 gap-x-6">
                <div>
                  <h4 className="text-lg font-semibold mb-5">KaHero Apps, Inc.</h4>
                  <div>Aug. 2021 - Present</div>
                </div>
                <div className="lg:col-span-2">
                  <h4 className="text-lg font-semibold mb-5">Senior Developer</h4>
                  <p className="mb-5">The team spent a lot of time in developing new features, enhancing UI/UX, and solving computational errors that boost customers&apos; retention rate.</p>
                  <p>Moreover, we architectured our mobile and web applications using the ideas of Uncle Bob&apos;s The Clean Architecture, which made maintaining the applications better and making it easy to scale in terms of codebase.</p>
                </div>
              </div>
              <div className="grid grid-cols-3 gap-x-6 mt-12">
                <div>
                  <h4 className="text-lg font-semibold mb-5">Bai Web and Mobile Lab</h4>
                  <div>Apr. 2018 - Aug. 2021</div>
                </div>
                <div className="lg:col-span-2">
                  <h4 className="text-lg font-semibold mb-5">Developer</h4>
                  <p className="mb-5">The team worked on developing, customizing, tailoring the ERPNext for various industries such as: (1) property management systems, (2) POS systems, (3) veterinary information and booking systems, and (4) pharmaceutical sales and inventory systems.</p>
                </div>
              </div>
              <div className="grid grid-cols-3 gap-x-6 mt-12">
                <div>
                  <h4 className="text-lg font-semibold mb-5">Bai Web and Mobile Lab</h4>
                  <div>Jan. 2017 - Jul. 2017</div>
                </div>
                <div className="lg:col-span-2">
                  <h4 className="text-lg font-semibold mb-5">Junior Developer</h4>
                  <p className="mb-5">The company explored ERPNext&apos;s potentials to the software industry market. We worked on coding script reports, customizing invoices&apos; forms in order to provide better contexts on clients&apos; sales and revenues.</p>
                  <p>The company has also worked in implementing a startup project to the local market.</p>
                </div>
              </div>
              <div className="grid grid-cols-3 gap-x-6 mt-12">
                <div>
                  <h4 className="text-lg font-semibold mb-5">XU - Social Development and Barangay Lumbia</h4>
                  <div>Jun. 2016 - Nov. 2016</div>
                </div>
                <div className="lg:col-span-2">
                  <h4 className="text-lg font-semibold mb-5">PHP Developer</h4>
                  <p className="mb-5">The teammates went to Barangay Lumbia in order to gain a better understanding of their profilling processes, and crafting a profiling system using CodeIgniter framework.</p>
                </div>
              </div>
            </div>
            <div>
              <h3 className="text-3xl font-bold border-b-2 border-gray-300 pb-4 mb-7">Summary</h3>
              <p>
                For the first 5 years of my career, Ivan have been helping in implementing various web/mobile apps to small/medium enterprises (SMEs)—Point-of-Sale (PoS) and Enterprise Resource Planning (ERP) business solutions.
              </p>
              <h3 className="text-3xl font-bold border-b-2 border-gray-300 pb-4 mb-7 mt-12">Skills</h3>
              <h4 className="text-lg font-semibold">Programming Languages</h4>
              <ul className="list-disc pl-5 mt-5 mb-5">
                <li className="mt-2">Python</li>
                <li className="mt-2">Dart</li>
                <li className="mt-2">JavaScript</li>
                <li className="mt-2">TypeScript</li>
                <li className="mt-2">Rust</li>
              </ul>
              <h4 className="text-lg font-semibold">Web & Mobile Frameworks</h4>
              <ul className="list-disc pl-5 mt-5 mb-5">
                <li className="mt-2">React.js</li>
                <li className="mt-2">Next.js</li>
                <li className="mt-2">Flutter</li>
              </ul>
              <h4 className="text-lg font-semibold">Backend Technologies</h4>
              <ul className="list-disc pl-5 mt-5 mb-5">
                <li className="mt-2">Frappe/ERPNext</li>
                <li className="mt-2">Cloud Firestore</li>
                <li className="mt-2">Cloud Functions</li>
                <li className="mt-2">Django</li>
                <li className="mt-2">FastAPI</li>
              </ul>
              <h3 className="text-3xl font-bold border-b-2 border-gray-300 pb-4 mb-7 mt-12">Education</h3>
              <h4 className="text-lg font-semibold">Xavier University - Ateneo de Cagayan</h4>
              <div className="mt-2">BS in Computer Science, 2018</div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
